### ISSUE TITLE
Fails to build with webkitgtk 2.16

### ISSUE THREAD

**Issue by jbicha** [Antergos/web-greeter#128]
webkitgtk 2.16 was released last week. Since new webkitgtk releases are often security releases, webkitgtk 2.16 will be packaged in stable Linux distros soon.

Build log excerpt
---------------------
`In file included from ../src/webkit2-extension.c:46:0:
/usr/include/webkitgtk-4.0/webkitdom/WebKitDOMCustom.h:20:2: error: #error "Only <webkitdom/webkitdom.h> can be included directly."
 #error "Only <webkitdom/webkitdom.h> can be included directly."
`

Suggested fix
------------------
I think you can just remove
 `#include <webkitdom/WebKitDOMCustom.h>`

**Comment by jbicha** [comment]
To clarify, this is with web-greeter 2.2.3.

It confused me a bit how 3.0 beta uses python but not meson and I guess you haven't actually done the name change for the 2.2 series yet.

**Comment by lots0logs** [comment]
The 2.2 series will not get a name change. It's being replaced by the 3.0 series. However, I've been waiting for getting distro packaging situated before making it official. Also I havent decided if I will keep the 2.2 series around until support for webkitgtk is ready in 3.0 (currently 3.0 requires qtwebengine). Personally I dont think its an issue but I am sure there are some that would disagree with me on that.
